name: Publish Package
on:
  workflow_dispatch:
    inputs:
      release-type:
        description: "Release type"
        required: false
        type: choice
        default: patch
        options:
          - patch
          - minor
          - major

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # Checkout project repository
      - name: Checkout
        uses: actions/checkout@v3

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"

      # Install dependencies (required by Run tests step)
      - name: Install dependencies
        run: npm ci

      # Tests
      - name: Run tests
        run: npm run test

      # Configure Git
      - name: Git configuration
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      # Bump package version
      - name: Bump release version
        run: npm version $RELEASE_TYPE -m "new release v%s"
        env:
          RELEASE_TYPE: ${{ github.event.inputs.release-type }}

      # Publish version to public repository
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_ACCESS_TOKEN }}
